### ISSUE TITLE
Validation against RegEx

### ISSUE THREAD

**Issue by demisx** [buunguyen/koa-req-validator#5]
Hello. I have this validation rule:

```ts
router.post(/^\/ads$/,
  validate({
    'classCode:body': [
      'require',
      'matches(/^[a-z]{0,6}$/)', // <- throws error below
      'Code cannot be empty and must contain 1-6 letters',
    ],
  }),
```

However, running it I get this error:

```
SyntaxError: Unexpected token / in JSON at position 0
[2]       at JSON.parse (<anonymous>)
[2]       at /Users/dm/projects/project/node_modules/koa-req-validator/lib/index.js:30:23
[2]       at Array.map (<anonymous>)
[2]       at /Users/dm/projects/project/node_modules/koa-req-validator/lib/index.js:29:29
[2]       at Generator.next (<anonymous>)
```

What's the correct to validate against a RegEx?

**Comment by buunguyen** [comment]
Would this work?

```
'matches("^[a-z]{0,6}$")'
```

**Comment by demisx** [comment]
Yeah, I've tried that too. Getting this error instead:

```
SyntaxError: Unexpected end of JSON input
[2]       at JSON.parse (<anonymous>)
...
```

**Comment by buunguyen** [comment]
Fixed in v0.2.1. Please check. Thanks!

**Comment by thearavind** [comment]
Facing the same error while using `equals(match)` and `isIn([match1, match2])` validators

 I'm Using the latest version of koa-req-validator V0.2.1

`time: ['require', 'isIn([AM, PM])', 'Time must be AM or PM']`

`SyntaxError: Unexpected token A in JSON at position 0
      at JSON.parse (<anonymous>)
      at /home/aravind/coding/js/GraphQL101/node_modules/koa-req-validator/lib/index.js:31:23
`

**Comment by buunguyen** [comment]
Would `isIn(["AM", "PM"])` work?

**Comment by thearavind** [comment]
Tried that also getting `SyntaxError: Unexpected end of JSON input`
