### ISSUE TITLE
Validation with header as another scope

### ISSUE THREAD

**Issue by knife-s** [buunguyen/koa-req-validator#6]
Hello, I need to validate a header in the request with certain value, can you please add support for headers? I did it but I lost my changes everytime I wrote npm install.

Thank you, this is a very useful module!

**Comment by ngphi** [comment]
Hi @knife-s ,

It's a good idea. Could you give me some use cases ? How did you implement the feature in your local ?

It would be helpful for me to start implementing the feature.

**Comment by knife-s** [comment]
> Hi @knife-s ,
> 
> It's a good idea. Could you give me some use cases ? How did you implement the feature in your local ?
> 
> It would be helpful for me to start implementing the feature.

Sorry for late reply.

One useful use-case would be when You need to validate a custom header such as "X-custom-Token: xxxx" to return custom data based on it.

**Comment by buunguyen** [comment]
Header validation is already support (thanks to @nphi1212).
